apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pokemon-search-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: pokemon-search-static-ip
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/pre-shared-cert: pokemon-cert
spec:
  rules:
    - host: pokemon-search.aniweb.info
      http:
        paths:
          - backend:
              serviceName: pokemon-search-service
              servicePort: 8081
