apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pokemon-search-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: pokemon-search-service
              servicePort: 8081
