apiVersion: v1
kind: Service
metadata:
  name: pokemon-search
  labels:
    app: pokemon-search
spec:
  type: NodePort
  selector:
    app: pokemon-search
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
